
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202204c
    username: teranishidaina
    password: postgres
server:
  servlet:
    context-path: /ec-202204c
